### 1.Numpy基本操作

In [4]:
# 
import numpy as np

# 创建numpy数组
"""
np.array([
    [1,3,5],
    [4,6,9]
])

"""

array=np.array([
    [1,3,5],
    [4,6,9]
])

#### 1.1 列表转为矩阵

In [5]:
array

array([[1, 3, 5],
       [4, 6, 9]])

#### 1.2 维度

In [4]:
array.ndim

2

#### 1.3 行数和列数()

In [5]:
array.shape

(2, 3)

#### 1.4 元素个数

In [6]:
array.size

6

### 2.Numpy创建array

#### 2.1 一维array创建

In [7]:
# 一维array
a = np.array([2,23,4], dtype=np.int32) # np.int默认为int32
a

array([ 2, 23,  4])

In [8]:
a.dtype

dtype('int32')

#### 2.2 多维array创建

In [9]:
# 多维array
a = np.array([[2,3,4],
              [3,4,5]])
a

array([[2, 3, 4],
       [3, 4, 5]])

#### 2.3 创建全零数组

In [10]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### 2.4 创建全1数据

In [11]:
a = np.ones((3,4))
a*2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

#### 2.5 创建全空数组

In [12]:
# 创建全空数组，其实每个值都是接近于零的数
a = np.empty((5,5))
a

array([[6.23042070e-307, 3.56043053e-307, 1.60219306e-306,
        7.56571288e-307, 3.22651328e-307],
       [8.45599366e-307, 7.56593017e-307, 1.11261027e-306,
        1.11261502e-306, 1.42410839e-306],
       [7.56597770e-307, 6.23059726e-307, 1.42419530e-306,
        7.56599128e-307, 1.42417629e-306],
       [8.45593934e-307, 6.89805151e-307, 1.11260144e-306,
        6.89812281e-307, 1.42418172e-306],
       [1.37961641e-306, 1.39071445e-307, 8.45610231e-307,
        2.18568966e-312, 2.10077583e-312]])

#### 2.6 创建连续数组

In [13]:
# 创建连续数组,# 10-20的数据，步长为2
a = np.arange(10,21,2) 
a

array([10, 12, 14, 16, 18, 20])

#### 2.7 reshape操作

In [14]:
# 使用reshape改变上述数据的形状
b = a.reshape((2,3))
c=b.reshape((3,2))
b,c

(array([[10, 12, 14],
        [16, 18, 20]]),
 array([[10, 12],
        [14, 16],
        [18, 20]]))

#### 2.8 创建连续型数据

In [15]:
# 创建线段型数据,# 开始端1，结束端10，且分割成20个数据，生成线段
a = np.linspace(1,10,20) 
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

#### 2.9 linspace的reshape操作

In [16]:
# 同时也可以reshape
b = a.reshape((5,4))
b

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

### 3.Numpy基本运算

#### 3.1 一维矩阵运算

In [17]:
import numpy as np
# 一维矩阵运算
a = np.array([10,20,30,40])
b = np.arange(4)
a,b

(array([10, 20, 30, 40]), array([0, 1, 2, 3]))

In [18]:
#矩阵减法  对应元素相减
a - b

array([10, 19, 28, 37])

In [19]:
# 矩阵乘法，对应元素相乘
a*b

array([  0,  20,  60, 120])

In [20]:
b

array([0, 1, 2, 3])

In [21]:
# 在Numpy中，想要求出矩阵中各个元素的乘方需要依赖双星符号 **，以二次方举例，即：
b**2

array([0, 1, 4, 9], dtype=int32)

In [22]:
# Numpy中具有很多的数学函数工具?
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

In [23]:
# 逻辑判断
print(b<2)

[ True  True False False]


In [24]:
# 逻辑判断
a = np.array([1,1,4,3])
b = np.arange(4)
print(a==b)

[False  True False  True]


#### 3.2 多维矩阵运算

In [25]:
# 二维矩阵
a=np.array([[1,1],[0,1]])
a

array([[1, 1],
       [0, 1]])

In [27]:
b1=np.arange(4)
b=b1.reshape((2,2))
b

array([[0, 1],
       [2, 3]])

In [32]:
# 矩阵乘法
a.dot(b)
# np.dot(a,b)

array([[2, 4],
       [2, 3]])

In [33]:
# 注意矩阵乘法中两个矩阵的顺序
b.dot(a)
# np.dot(b,a)

array([[0, 1],
       [2, 5]])

In [34]:
#  random方法生成[0.0, 1.0)之间的随机数
a = np.random.random((2,4))
a

array([[0.03455252, 0.00834353, 0.17422714, 0.15835058],
       [0.02146929, 0.42639212, 0.50287011, 0.59272438]])

In [36]:
# 汇总
np.sum(a) 

1.9189296659073687

In [37]:
# 最小值
np.min(a)

0.00834353070326943

In [38]:
#最大值
np.max(a)

0.5927243752283647

In [41]:
# 按照行或列进行汇总，axis=0：以列作为查找单元， axis=1：以行作为查找单元
a=np.array([[1,2],[3,4]])
b=np.sum(a,axis=1)
c=np.sum(a,axis=0)
a,b,c

(array([[1, 2],
        [3, 4]]),
 array([3, 7]),
 array([4, 6]))

In [44]:
#  axis=1 按照行查找 每行最小值
b=np.min(a,axis=1)
b

array([1, 3])

In [45]:
# axis=0 按照列查找， 每列最大值
c=np.max(a,axis=0)
c

array([3, 4])

#### 3.3 基本计算

In [46]:
a = np.arange(2,14).reshape((3,4))
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [47]:
# 最小元素索引
np.argmin(a) # 0

0

In [48]:
# 最大元素索引
np.argmax(a) # 11

11

In [49]:
# 求整个矩阵的均值
np.mean(a) # 7.5

7.5

In [50]:
# 中位数
np.median(a) # 7.5

7.5

In [52]:
# 非零元素的索引 （了解）
b2 = np.array([[0,5,9],
              [4,0,10]])
np.nonzero(b2)

(array([0, 0, 1, 1], dtype=int64), array([1, 2, 0, 2], dtype=int64))

In [53]:
# # 非零元素的索引 （了解）
c = np.array([[0,5,9],
              [4,0,10],
              [1,1,0]])
np.nonzero(c)

(array([0, 0, 1, 1, 2, 2], dtype=int64),
 array([1, 2, 0, 2, 0, 1], dtype=int64))

In [54]:
#向量排序
np.sort(c)

array([[ 0,  5,  9],
       [ 0,  4, 10],
       [ 0,  1,  1]])

In [56]:
# 矩阵转置
np.transpose(c)
# c.T

array([[ 0,  4,  1],
       [ 5,  0,  1],
       [ 9, 10,  0]])

### 4.Numpy索引与切片

In [58]:
# 3-14的值
a = np.arange(3,15)
a

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
a[3]

6

In [60]:
b=a.reshape(3,4)
b

array([[ 3,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [61]:
b[2]

array([11, 12, 13, 14])

In [62]:
b[0][2]

5

In [66]:
b[0,2]

5

In [67]:
"""
[[ 3,  4,  5,  6],
 [ 7,  8,  9, 10],
 [11, 12, 13, 14]]
"""
# list切片操作,1:3表示从索引1到索引3（不包括3）#[8,9]
b[1,1:3] 

array([8, 9])

In [68]:
for row in b:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [69]:
# 如果要打印列，则进行转置即可
for col in b.T:
    print(col)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [70]:
# 多维转换为1维
b.flatten()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 5.Numpy array合并

#### 5.1 数组合并

In [73]:
# vertical stack 上下合并,对括号的两个整体操作。
a = np.array([1,1,1])
b = np.array([2,2,2])
a

array([1, 1, 1])

In [74]:
c=np.vstack((a,b))
c

array([[1, 1, 1],
       [2, 2, 2]])

In [75]:
# （3,）表示数组
a.shape
# a转换为3行1列的矩阵
# a.reshape(3,1)
# 1行3列
a.reshape(1,3)

array([[1, 1, 1]])

In [76]:
c.shape

(2, 3)

In [77]:
# horizontal stack左右合并
d= np.hstack((a,b))
d

array([1, 1, 1, 2, 2, 2])

In [78]:
d.shape

(6,)

#### 5.2 数组转置为矩阵

In [79]:
# np.newaxis:增加一个维度,数组转换为矩阵
# [1 1 1]变为[[1 1 1]],行轴上增加一个维度
b=a[np.newaxis,:]
b

array([[1, 1, 1]])

In [80]:
# (3,)变为(1, 3)
b.shape 

(1, 3)

In [81]:
# 列方向增加一个维度
c=a[:,np.newaxis]
c

array([[1],
       [1],
       [1]])

#### 5.3 多个矩阵合并

In [82]:
a = np.array([1,3,5])
b = np.array([2,4,6])
a

array([1, 3, 5])

In [83]:
a = a[:,np.newaxis] # 数组转为矩阵
a

array([[1],
       [3],
       [5]])

In [84]:
b = b[:,np.newaxis] # 数组转为矩阵
b

array([[2],
       [4],
       [6]])

In [85]:
# axis=0纵向合并
np.concatenate((a,b,a),axis=0)

array([[1],
       [3],
       [5],
       [2],
       [4],
       [6],
       [1],
       [3],
       [5]])

In [86]:
# axis=1横向合并
np.concatenate((a,b),axis=1)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### 5.4 合并例子

In [87]:
a = np.arange(8).reshape(2,4)
b = np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [88]:
# axis=0多个矩阵纵向合并
np.concatenate((a,b),axis=0)

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [89]:
# axis=1多个矩阵横向合并
np.concatenate((a,b),axis=1)

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

### 6.Numpy array分割

#### 6.1 构造3行4列矩阵

In [90]:
a=np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### 6.2 等量分割

In [91]:
# 等量分割
# 纵向分割同横向合并的axis
np.split(a, 2, axis=1)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [92]:
# 纵向分割
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [93]:
# 横向分割同纵向合并的axis
np.split(a,3,axis=0)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [94]:
# 横向分割
np.vsplit(a,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

### 7.Numpy copy与 =

#### 7.1 =赋值方式会带有关联性

In [39]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [40]:
b = a
c = a
d = b
a[0] = 11
a

array([11,  1,  2,  3])

In [41]:
b

array([11,  1,  2,  3])

In [42]:
c

array([11,  1,  2,  3])

In [43]:
d

array([11,  1,  2,  3])

In [44]:
b is a # True

True

In [45]:
c is b # True

True

In [46]:
d is a # True

True

In [47]:
d[1:3] = [22,33]
a

array([11, 22, 33,  3])

In [ ]:
b

In [ ]:
c

#### 7.2 copy()赋值方式没有关联性

In [48]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [49]:
b =a.copy() # deep copy
b

array([0, 1, 2, 3])

In [50]:
a[3] = 33
a

array([ 0,  1,  2, 33])

In [51]:
b

array([0, 1, 2, 3])

### 8.广播机制

numpy数组间的基础运算是一对一，也就是`a.shape==b.shape`，但是当两者不一样的时候，就会自动触发广播机制，如下例子：

In [96]:
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])

b = np.array([0,1,2])
"""
b为了和a进行匹配，自动扩展为:
[[0,1,2],
[0,1,2],
[0,1,2],
[0,1,2]]
"""
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [97]:
# 矩阵与常数相加
a+3

array([[ 3,  3,  3],
       [13, 13, 13],
       [23, 23, 23],
       [33, 33, 33]])

In [98]:
3+a

array([[ 3,  3,  3],
       [13, 13, 13],
       [23, 23, 23],
       [33, 33, 33]])

In [99]:
# tile，原矩阵进行横向或纵向复制，行重复1次，列重复1次
b = np.tile([0,1,2],(1,1))
b

array([[0, 1, 2]])

In [100]:
# 对行重复2次，列重复1次
b = np.tile([0,1,2],(2,1))
b

array([[0, 1, 2],
       [0, 1, 2]])

In [101]:
# 对行重复1次，列重复2次
b = np.tile([0,1,2],(1,2))
b

array([[0, 1, 2, 0, 1, 2]])

In [102]:
# 对行重复3次，列重复2次
b = np.tile([0,1,2],(3,2))
b

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [103]:
#原理分析
a=np.ones((2,3))
b=np.arange(3)
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [104]:
b

array([0, 1, 2])

In [18]:
a.shape

(2, 3)

In [20]:
b.shape

(3,)

In [21]:
a+b

array([[1., 2., 3.],
       [1., 2., 3.]])

### 9.常用函数

#### 9.1 常用统计函数

In [ ]:
a = np.array([4, 9, 16])

In [57]:
#开方
np.sqrt(a)

array([[0.        , 0.        , 0.        ],
       [3.16227766, 3.16227766, 3.16227766],
       [4.47213595, 4.47213595, 4.47213595],
       [5.47722558, 5.47722558, 5.47722558]])

In [58]:
# 绝对值
np.abs(np.array([-1,2,3]))

array([1, 2, 3])

In [59]:
# 平方
np.square(a)

array([[  0,   0,   0],
       [100, 100, 100],
       [400, 400, 400],
       [900, 900, 900]], dtype=int32)

In [22]:
#去重
np.unique(np.array([1, 2, 3, 3, 2,4]))

array([1, 2, 3, 4])

#### 9.2 逻辑数组

In [61]:
a=np.arange(9)

In [62]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
c=b>5
c

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True]])

In [64]:
# 布尔转换为0，1
c+0

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1]])

In [65]:
np.sum(c==1)

3

In [28]:
np.sum(c==True)

3

#### 9.3 np.argmax()

函数原型为：`numpy.argmax(a, axis=None, out=None)`.

函数表示返回沿轴axis最大值的索引。

In [29]:
"""
axis属性
axis=0表示按列操作，也就是对比当前列，找出最大值的索引
"""
x = [[1,3,3],
     [7,5,2]]
np.argmax(x,axis=0)

array([1, 1, 0], dtype=int64)

In [30]:
"""
axis属性
axis=1表示按行操作，也就是对比当前行，找出最大值的索引
"""
np.argmax(x,axis=1)

array([1, 0], dtype=int64)

In [31]:
np.argmax(x)

3

#### 9.4 求取精度

In [32]:
# 
np.around([-0.6,1.2798,2.357,9.67,13], decimals=0)#取指定位置的精度

array([-1.,  1.,  2., 10., 13.])

In [33]:
np.around([1.2798,2.357,9.67,13], decimals=1)

array([ 1.3,  2.4,  9.7, 13. ])

In [34]:
np.around([1.2798,2.357,9.67,13], decimals=2)

array([ 1.28,  2.36,  9.67, 13.  ])

计算沿指定轴第N维的离散差值

In [67]:
x = np.arange(1 , 16).reshape((3 , 5))
x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [68]:
"""
沿着指定轴计算第N维的离散差值
"""
np.diff(x,axis=1) 

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [37]:
np.diff(x,axis=0) 

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

取整

In [38]:
np.floor([-0.6,-1.4,-0.1,-1.8,0,1.4,1.7])

array([-1., -2., -1., -2.,  0.,  1.,  1.])

In [39]:
# 取上限
np.ceil([1.2,1.5,1.8,2.1,2.0,-0.5,-0.6,-0.3])

array([ 2.,  2.,  2.,  3.,  2., -0., -0., -0.])

查找

利用np.where实现小于0的值用0填充吗，大于0的数不变！
np.where(condition, x, y)
满足条件(condition)，输出x，不满足输出y。

In [69]:
x = np.array([[1, 0],
       [2, -2],
     [-2, 1]])
x

array([[ 1,  0],
       [ 2, -2],
       [-2,  1]])

In [70]:
np.where(x>0,x,0)

array([[1, 0],
       [2, 0],
       [0, 1]])